version: '3'
networks:
  default:
services:
  mysql:
    container_name: mysql
    working_dir: '/root/'
    build: 
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    networks:
      - default
    ports:
      - "3306:3306"
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./data/mysql:/var/lib/mysql
  python:
    depends_on:
      - mysql
    container_name: 'python'
    restart: always
    build: 
      context: .
      dockerfile: ./docker/python/Dockerfile
    working_dir: '/app/'
    tty: true
    networks:
      - default
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
  nginx:
    depends_on:
      - python
    container_name: nginx
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    networks:
      - default
    ports:
      - "80:80"
