version: '3'
networks:
  default:
services:
  mysql:
    container_name: mysql
    working_dir: '/root/'
    build: 
      context: .
      dockerfile: ./container/mysql/Dockerfile
    networks:
      - default
    ports:
      - "3306:3306"
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./data:/var/lib/data
  nginx:
    container_name: nginx
    working_dir: '/root/'
    build: 
      context: .
      dockerfile: ./container/nginx/Dockerfile
    networks:
      - default
    ports:
      - "80:80"
  python:
    container_name: 'python'
    restart: always
    build: 
      context: .
      dockerfile: ./container/python/Dockerfile
    working_dir: '/app/'
    tty: true
    networks:
      - default
    volumes:
      - ./src:/app
      - ./container/python/data:/app/data
