version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'python'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./data:/root/data
      - ./src:/root/src
      - ./requirements.txt:/root/requirements.txt