"""added columns into item/user

Revision ID: 1d3c01135b58
Revises: c5692414ce87
Create Date: 2023-01-23 04:43:05.719947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3c01135b58'
down_revision = 'c5692414ce87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('item', sa.Column('seeded', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('seeded', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'seeded')
    op.drop_column('user', 'deleted')
    op.drop_column('item', 'seeded')
    op.drop_column('item', 'deleted')
    # ### end Alembic commands ###
