"""fix models

Revision ID: 4e7db357cb40
Revises: bc88365fb555
Create Date: 2023-01-23 10:42:02.264527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e7db357cb40'
down_revision = 'bc88365fb555'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
