"""fix column name into item

Revision ID: 5e0ce2058f7f
Revises: 9dbd2e35a284
Create Date: 2023-01-23 09:59:54.656881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0ce2058f7f'
down_revision = '9dbd2e35a284'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('deleted_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'deleted_at')
    # ### end Alembic commands ###
