"""added columns into item

Revision ID: 9dbd2e35a284
Revises: 1d3c01135b58
Create Date: 2023-01-23 09:57:42.015581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9dbd2e35a284'
down_revision = '1d3c01135b58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_ja_0900_as_cs', length=255),
               nullable=True)
    op.alter_column('item', 'price',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('item', 'country',
               existing_type=mysql.VARCHAR(collation='utf8mb4_ja_0900_as_cs', length=255),
               nullable=True)
    op.drop_column('item', 'deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.alter_column('item', 'country',
               existing_type=mysql.VARCHAR(collation='utf8mb4_ja_0900_as_cs', length=255),
               nullable=False)
    op.alter_column('item', 'price',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('item', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_ja_0900_as_cs', length=255),
               nullable=False)
    # ### end Alembic commands ###
