"""removing deleted_at from commonModel

Revision ID: a9077619c002
Revises: 4cb1764e5708
Create Date: 2023-01-27 07:45:04.586962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9077619c002'
down_revision = '4cb1764e5708'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_country', table_name='item')
    op.drop_index('ix_item_name', table_name='item')
    op.drop_table('item')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_name', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('seeded', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_ja_0900_as_cs', length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_ja_0900_as_cs', length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_ja_0900_as_cs', length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_ja_0900_as_cs',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.create_table('item',
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('seeded', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_ja_0900_as_cs', length=255), nullable=True),
    sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('country', mysql.VARCHAR(collation='utf8mb4_ja_0900_as_cs', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_ja_0900_as_cs',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_item_name', 'item', ['name'], unique=False)
    op.create_index('ix_item_country', 'item', ['country'], unique=False)
    # ### end Alembic commands ###
