"""fix column item.deleted_at

Revision ID: bc88365fb555
Revises: 5695b596f6cc
Create Date: 2023-01-23 10:12:49.066063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc88365fb555'
down_revision = '5695b596f6cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'deleted_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'deleted_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
