"""unite mModelBase

Revision ID: be7949282fa2
Revises: 4e7db357cb40
Create Date: 2023-01-23 10:51:25.430693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be7949282fa2'
down_revision = '4e7db357cb40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('user', 'deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('user', 'deleted_at')
    # ### end Alembic commands ###
