"""added tables-args

Revision ID: c5692414ce87
Revises: 3a7bf275f039
Create Date: 2023-01-21 01:29:15.142137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5692414ce87'
down_revision = '3a7bf275f039'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
